name: mini_flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6
  cupertino_icons: ^0.1.2
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  image: ^2.0.7
  provide: ^1.0.1
  tripledes: ^2.1.0
  pointycastle: ^1.0.0-rc4
  json_serializable: ^2.0.0
  redux_persist_flutter: ^0.8.2
  flutter_downloader: ^1.4.1
  permission_handler: ^3.0.0
  flutter_webview_plugin: ^0.3.10+1
  flutter_markdown: ^0.3.4
  dio: ^3.0.8
  url_launcher: ^5.1.2
  flutter_html:
    git:
      url: https://github.com/jlcool/flutter_html
      ref: tableAlign
  audioplayers: ^0.15.0
  flutter_sound: ^2.1.1
  uuid: ^2.0.4
  http: ^0.12.0
  path_provider: ^1.4.0
  charts_flutter: ^0.8.1
  flutter_i18n:
    git:
      url: https://github.com/jlcool/flutter_i18n
  oktoast: ^2.1.1
  fluttertoast: ^3.0.3
  flutter_calendar_carousel: ^1.3.5
  flutter_sticky_header: ^0.4.0
  cached_network_image: ^2.0.0
  flutter_keyboard_visibility: ^2.0.0
  flutter_cache_manager: ^1.1.3
  package_info: ^0.4.0+2
  image_picker: ^0.6.1+4
  sticky_headers: ^0.1.7
  protobuf: ^0.13.9
  jpush_flutter:
    git:
      url: https://github.com/jlcool/jpush-flutter-plugin
  material_design_icons_flutter: ^3.2.3595
  csv: ^4.0.3
  after_layout: ^1.0.7
  flutter_aes:
    git:
      url: https://github.com/jlcool/flutter_aes
  alipay_kit: 1.1.0
  fake_weibo: 0.2.1
  fake_wechat: ^0.3.4
  tencent_kit:
    git:
      url: https://github.com/v7lin/fake_tencent
  aliossflutter:
    git:
      url: https://github.com/jlcool/aliossflutter
  flutter_zip_archive:
    git:
      url: https://github.com/jlcool/flutter_zip_archive
  flutter_shared_data:
    git:
      url: https://github.com/jlcool/flutter_shared_data
  photo_view: ^0.9.2
  reorderables: ^0.3.2
  qr_flutter: ^2.0.0+51
  device_info: ^0.4.0+2
  flutter_tai: ^0.0.4
  

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  kiwi_generator: ^0.4.0

module:
  androidX: true

dependency_overrides:
  flutter_svg: 0.18.0
  markdown:
    git:
      url: https://github.com/jlcool/markdown
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
